// Yearly money distribution -------------------------------------------------
const yearlyDistribution = {
  receivedIncome: 7870.45,
  shouldHave: 16471.97,
  actuallyHave: 16471.97,
  extra: 0.0,
};

// Fixed savings -------------------------------------------------------------
const fixedSavings = [
  { name: "Emergency", total: 1000, saved: 0, used: 0, available: 0 },
  {
    name: "6 Months Living Support",
    total: 12000,
    saved: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Dentist Checkup",
    total: 100,
    saved: 100,
    used: 0,
    available: 100,
  },
  {
    name: "Business & Real Estate",
    total: "Unlimited",
    saved: 180,
    used: 80.5,
    available: 99.5,
  },
  { name: "Gold", total: "Unlimited", saved: 0, used: 0, available: 0 },
  { name: "Mortgage Deposit", total: 50000, saved: 0, used: 0, available: 0 },
  {
    name: "Relocation",
    total: 3000,
    saved: 3000,
    used: 123.26,
    available: 2876.74,
  },
  {
    name: "Tattoo Removal",
    total: 220,
    saved: 220,
    used: 0,
    available: 220,
  },
  {
    name: "Car",
    total: 15000,
    saved: 9684.95,
    used: 0,
    available: 9684.95,
  },
  { name: "Gyno Treatment", total: 2500, saved: 0, used: 0, available: 0 },
  { name: "Watch", total: 600, saved: 0, used: 0, available: 0 },
  { name: "Skydiving License", total: 3000, saved: 0, used: 0, available: 0 },
  {
    name: "Sports Equipment",
    total: 4000,
    saved: 0,
    used: 0,
    available: 0,
  },
  { name: "Pilot License", total: 12000, saved: 0, used: 0, available: 0 },
];

// Yearly expenses -----------------------------------------------------------
const yearlyExpenses = [
  {
    name: "Summer Holiday",
    startMonth: "August",
    total: 500,
    totalShouldBe: "500 - 1200",
    monthlySaving: 41.67,
    saved: 1200,
    missed: 0,
    used: 427,
    available: 773,
  },
  {
    name: "Winter Holiday",
    startMonth: "January",
    total: 0,
    totalShouldBe: "500 - 1200",
    monthlySaving: 0,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Travelling",
    startMonth: "December",
    total: 0,
    totalShouldBe: "2000 - 5000",
    monthlySaving: 0,
    saved: 2000,
    missed: 0,
    used: 0,
    available: 2000,
  },
  {
    name: "Phone",
    startMonth: "August",
    total: 2200,
    totalShouldBe: "2200.00",
    monthlySaving: 45.83,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Laptop",
    startMonth: "August",
    total: 3000,
    totalShouldBe: "5000.00",
    monthlySaving: 62.5,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Concerts",
    startMonth: "",
    total: 0,
    totalShouldBe: "500 - 1000",
    monthlySaving: 0,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Birthday Party",
    startMonth: "September",
    total: 0,
    totalShouldBe: "250 - 500",
    monthlySaving: 0,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Perfumes",
    startMonth: "August",
    total: 250,
    totalShouldBe: "250 - 500",
    monthlySaving: 20.83,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Spotify",
    startMonth: "January",
    total: 32,
    totalShouldBe: "32.00",
    monthlySaving: 2.67,
    saved: 32,
    missed: 0,
    used: 0,
    available: 32,
  },
  {
    name: "Car Insurance",
    startMonth: "",
    total: 0,
    totalShouldBe: "0.00",
    monthlySaving: 0,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Car Tax",
    startMonth: "",
    total: 0,
    totalShouldBe: "0.00",
    monthlySaving: 0,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Car MOT",
    startMonth: "",
    total: 0,
    totalShouldBe: "0.00",
    monthlySaving: 0,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Car Maintenance",
    startMonth: "",
    total: 0,
    totalShouldBe: "0.00",
    monthlySaving: 0,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Renovations",
    startMonth: "",
    total: 0,
    totalShouldBe: "1000.00",
    monthlySaving: 0,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Apparel",
    startMonth: "August",
    total: 1000,
    totalShouldBe: "1000 - 2000",
    monthlySaving: 83.33,
    saved: 0,
    missed: 0,
    used: 0,
    available: 0,
  },
  {
    name: "Eset Antivirus",
    startMonth: "July",
    total: 40,
    totalShouldBe: "40.00",
    monthlySaving: 3.33,
    saved: 3.33,
    missed: 0,
    used: 0,
    available: 3.33,
  },
];

// Monthly budget -----------------------------------------------------------
const monthlyBudget = {
  income: [{ name: "Hydrogenera", amount: 3000 }],
  essentials: {
    monthly: [
      {
        id: "nextMonth",
        items: [{ name: "Next Month Savings", amount: 465.83 }],
      },
      {
        id: "expenses",
        items: [
          { name: "One Drive", amount: 7.1 },
          { name: "iCloud", amount: 2.35 },
          { name: "Barber", amount: 25 },
          { name: "Meds", amount: 10 },
          { name: "Toiletries", amount: 0 },
          { name: "Transport", amount: 80 },
          { name: "Phone", amount: 0 },
          { name: "Sports", amount: 40 },
          { name: "Internet", amount: 0 },
          { name: "Bills", amount: 0 },
          { name: "Rent", amount: 0 },
        ],
      },
      {
        id: "savings",
        items: [
          { name: "Apparel Savings", amount: 0 },
          { name: "Eset Antivirus Savings", amount: 0 },
        ],
      },
    ],
    weekly: [{ name: "Food", amount: 100 }],
  },
  luxury: {
    percentage: 90,
    monthly: [
      {
        id: "expenses",
        items: [
          { name: "Little Things", amount: 10 },
          { name: "Massage", amount: 0 },
          { name: "Activities", amount: 0 },
          { name: "Birthday Present", amount: 50 },
          { name: "Going Out", amount: 80 },
        ],
      },
      {
        id: "savings",
        items: [
          { name: "Fixed Expenses Savings (20%+)", amount: 6324.34 },
          {
            name: "Mortgage Deposit Fixed Expenses Savings (10%)",
            amount: 0,
          },
          { name: "Summer Holiday Savings", amount: 0 },
          { name: "Winter Holiday Savings", amount: 0 },
          { name: "Travelling Savings", amount: 0 },
          { name: "Phone Savings", amount: 0 },
          { name: "Laptop Savings", amount: 0 },
          { name: "Concerts Savings", amount: 0 },
          { name: "Birthday Party Savings", amount: 0 },
          { name: "Perfumes Savings", amount: 0 },
          { name: "Spotify Savings", amount: 2.67 },
          { name: "Car Insurance Savings", amount: 0 },
          { name: "Car Tax Savings", amount: 0 },
          { name: "Car MOT Savings", amount: 0 },
          { name: "Renovations Savings", amount: 0 },
        ],
      },
    ],
    weekly: [
      { name: "Dating", amount: 30 },
      { name: "Going Out", amount: 20 },
      { name: "Eat Out", amount: 10 },
    ],
  },
  investments: {
    percentage: 10,
    monthly: [
      { name: "S&P500", amount: 63, percentage: 45 },
      {
        name: "Business & Real Estate Savings",
        amount: 62.99,
        percentage: 45,
      },
      { name: "Gold Savings", amount: 14, percentage: 10 },
    ],
  },
};

module.exports = {
  yearlyDistribution,
  fixedSavings,
  yearlyExpenses,
  monthlyBudget,
};
